# Generated by Django 5.1 on 2024-08-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_artist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listen',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
